# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segy_import_one.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_segy_import_one_Dialog(object):
    def setupUi(self, segy_import_one_Dialog):
        segy_import_one_Dialog.setObjectName(_fromUtf8("segy_import_one_Dialog"))
        segy_import_one_Dialog.resize(560, 351)
        self.file_path_lineEdit = QtGui.QLineEdit(segy_import_one_Dialog)
        self.file_path_lineEdit.setGeometry(QtCore.QRect(70, 10, 321, 22))
        self.file_path_lineEdit.setObjectName(_fromUtf8("file_path_lineEdit"))
        self.label = QtGui.QLabel(segy_import_one_Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 22))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.selectButton = QtGui.QPushButton(segy_import_one_Dialog)
        self.selectButton.setGeometry(QtCore.QRect(410, 10, 71, 23))
        self.selectButton.setObjectName(_fromUtf8("selectButton"))
        self.tableWidget = QtGui.QTableWidget(segy_import_one_Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 541, 271))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 225))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 0, item)
        self.revision_comboBox = QtGui.QComboBox(segy_import_one_Dialog)
        self.revision_comboBox.setGeometry(QtCore.QRect(430, 70, 111, 22))
        self.revision_comboBox.setObjectName(_fromUtf8("revision_comboBox"))
        self.revision_comboBox.addItem(_fromUtf8(""))
        self.revision_comboBox.addItem(_fromUtf8(""))
        self.revision_comboBox.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(segy_import_one_Dialog)
        self.label_2.setGeometry(QtCore.QRect(440, 40, 61, 22))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.data_format_comboBox = QtGui.QComboBox(segy_import_one_Dialog)
        self.data_format_comboBox.setGeometry(QtCore.QRect(430, 100, 111, 22))
        self.data_format_comboBox.setObjectName(_fromUtf8("data_format_comboBox"))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.data_format_comboBox.addItem(_fromUtf8(""))
        self.nsample_spinBox = QtGui.QSpinBox(segy_import_one_Dialog)
        self.nsample_spinBox.setGeometry(QtCore.QRect(431, 130, 111, 22))
        self.nsample_spinBox.setObjectName(_fromUtf8("nsample_spinBox"))
        self.label_3 = QtGui.QLabel(segy_import_one_Dialog)
        self.label_3.setGeometry(QtCore.QRect(330, 160, 71, 22))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.start_lineEdit = QtGui.QLineEdit(segy_import_one_Dialog)
        self.start_lineEdit.setGeometry(QtCore.QRect(410, 160, 61, 20))
        self.start_lineEdit.setObjectName(_fromUtf8("start_lineEdit"))
        self.step_lineEdit = QtGui.QLineEdit(segy_import_one_Dialog)
        self.step_lineEdit.setGeometry(QtCore.QRect(480, 160, 61, 20))
        self.step_lineEdit.setObjectName(_fromUtf8("step_lineEdit"))
        self.next_Button = QtGui.QPushButton(segy_import_one_Dialog)
        self.next_Button.setGeometry(QtCore.QRect(370, 320, 75, 23))
        self.next_Button.setObjectName(_fromUtf8("next_Button"))
        self.cancelButton = QtGui.QPushButton(segy_import_one_Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(470, 320, 75, 23))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))

        self.retranslateUi(segy_import_one_Dialog)
        self.revision_comboBox.setCurrentIndex(1)
        self.data_format_comboBox.setCurrentIndex(1)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), segy_import_one_Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(segy_import_one_Dialog)

    def retranslateUi(self, segy_import_one_Dialog):
        segy_import_one_Dialog.setWindowTitle(_translate("segy_import_one_Dialog", "Import SEGY", None))
        self.label.setText(_translate("segy_import_one_Dialog", "Input File:", None))
        self.selectButton.setText(_translate("segy_import_one_Dialog", "Select", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("segy_import_one_Dialog", "SEG-Y Revision", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("segy_import_one_Dialog", "Data Format", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("segy_import_one_Dialog", "Number of samples", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("segy_import_one_Dialog", "Z Range", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("segy_import_one_Dialog", "In-line Range", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("segy_import_one_Dialog", "Cross-line Range", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("segy_import_one_Dialog", "X-coordinate Range", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("segy_import_one_Dialog", "Y-coordinate Range", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("segy_import_one_Dialog", "Quick Scan Result", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.revision_comboBox.setItemText(0, _translate("segy_import_one_Dialog", "0", None))
        self.revision_comboBox.setItemText(1, _translate("segy_import_one_Dialog", "1", None))
        self.revision_comboBox.setItemText(2, _translate("segy_import_one_Dialog", "2", None))
        self.label_2.setText(_translate("segy_import_one_Dialog", "Actually Use", None))
        self.data_format_comboBox.setItemText(0, _translate("segy_import_one_Dialog", "From file header", None))
        self.data_format_comboBox.setItemText(1, _translate("segy_import_one_Dialog", "1 - Floating point", None))
        self.data_format_comboBox.setItemText(2, _translate("segy_import_one_Dialog", "2 - Integer (32 bits)", None))
        self.data_format_comboBox.setItemText(3, _translate("segy_import_one_Dialog", "3 - Integer (64 bits)", None))
        self.data_format_comboBox.setItemText(4, _translate("segy_import_one_Dialog", "5 - IEEE float (32 bits)", None))
        self.data_format_comboBox.setItemText(5, _translate("segy_import_one_Dialog", "8 - Signed char (8 bits)", None))
        self.data_format_comboBox.setItemText(6, _translate("segy_import_one_Dialog", "1 - Floating point (byte swapped)", None))
        self.data_format_comboBox.setItemText(7, _translate("segy_import_one_Dialog", "2 - Integer (32 bits) (byte swapped)", None))
        self.data_format_comboBox.setItemText(8, _translate("segy_import_one_Dialog", "3 - Integer (64 bits) (byte swapped)", None))
        self.data_format_comboBox.setItemText(9, _translate("segy_import_one_Dialog", "5 - IEEE float (32 bits) (byte swapped)", None))
        self.label_3.setText(_translate("segy_import_one_Dialog", "start / inteval", None))
        self.next_Button.setText(_translate("segy_import_one_Dialog", "Next", None))
        self.cancelButton.setText(_translate("segy_import_one_Dialog", "Cancel", None))

